version: "3.9"
services:
  db:
    image: postgres
    container_name: postgres_orm
    env_file:
      - .env.sample
    environment:
      - POSTGRES_DB = DB_NAME
      - POSTGRES_USER = DB_USER
      - POSTGRES_PASSWORD = DB_USER_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_orm
    depends_on: [db]
    ports:
      - "5051:80"
    env_file:
      - .env.sample
    environment:
      - PGADMIN_DEFAULT_EMAIL=PGADMIN_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=PGADMIN_PASSWORD
    volumes:
      - pg_admin:/var/lib/pgadmin

  web:
    build: .
    container_name: django_orm
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on: [db]

volumes:
  postgres_data:
  pg_admin:
  src: